package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import presenter.ControleUsuariosPresenter;
import repository.IUsuarioRepository;
import repository.INotificacaoRepository;
import com.mycompany.acessousuario.model.Usuario;

/**
 *
 * @author marqu
 */
public class ControleUsuariosView extends javax.swing.JInternalFrame {

    private final ControleUsuariosPresenter presenter;
    
    public ControleUsuariosView(IUsuarioRepository usuarioRepository,
                                INotificacaoRepository notificacaoRepository,
                                Usuario usuarioAutenticado) {
        initComponents();
        this.presenter = new ControleUsuariosPresenter(this, usuarioRepository, notificacaoRepository, usuarioAutenticado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jbAutorizar = new javax.swing.JButton();
        jbRecusar = new javax.swing.JButton();
        jbPromover = new javax.swing.JButton();
        jbRemoverAdmin = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jcbPendentes = new javax.swing.JCheckBox();
        jcbAdministradores = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Controle de Usuários");

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login", "Tipo", "Status", "Data Cadastro", "Notif. Enviadas", "Notif. Lidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUsuarios.setColumnSelectionAllowed(true);
        jtUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtUsuarios);
        jtUsuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jbAutorizar.setText("Autorizar Usuário");
        jbAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAutorizarActionPerformed(evt);
            }
        });

        jbRecusar.setText("Recusar Usuário");
        jbRecusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRecusarActionPerformed(evt);
            }
        });

        jbPromover.setText("Promover a Administrador");
        jbPromover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPromoverActionPerformed(evt);
            }
        });

        jbRemoverAdmin.setText("Remover Administrador");
        jbRemoverAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverAdminActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar Lista");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAutorizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRecusar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPromover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAtualizar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAutorizar)
                    .addComponent(jbRecusar)
                    .addComponent(jbPromover)
                    .addComponent(jbRemoverAdmin)
                    .addComponent(jbAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jcbPendentes.setText("Mostrar apenas pendentes");
        jcbPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPendentesActionPerformed(evt);
            }
        });

        jcbAdministradores.setText("Mostrar apenas administradores");
        jcbAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAdministradoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbPendentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbAdministradores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPendentes)
                    .addComponent(jcbAdministradores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAutorizarActionPerformed
        presenter.autorizarUsuario();
    }//GEN-LAST:event_jbAutorizarActionPerformed

    private void jbRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRecusarActionPerformed
        presenter.recusarUsuario();
    }//GEN-LAST:event_jbRecusarActionPerformed

    private void jbPromoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPromoverActionPerformed
        presenter.promoverAdministrador();
    }//GEN-LAST:event_jbPromoverActionPerformed

    private void jbRemoverAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverAdminActionPerformed
        presenter.removerAdministrador();
    }//GEN-LAST:event_jbRemoverAdminActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        presenter.carregarUsuarios();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jcbPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPendentesActionPerformed
        presenter.aplicarFiltros();
    }//GEN-LAST:event_jcbPendentesActionPerformed

    private void jcbAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAdministradoresActionPerformed
        presenter.aplicarFiltros();
    }//GEN-LAST:event_jcbAdministradoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbAutorizar;
    private javax.swing.JButton jbPromover;
    private javax.swing.JButton jbRecusar;
    private javax.swing.JButton jbRemoverAdmin;
    private javax.swing.JCheckBox jcbAdministradores;
    private javax.swing.JCheckBox jcbPendentes;
    private javax.swing.JTable jtUsuarios;
    // End of variables declaration//GEN-END:variables
    
    public JTable getJTable() {
        return jtUsuarios;
    }
    
    public JButton getJbAutorizar() {
        return jbAutorizar;
    }
    
    public JButton getJbRecusar() {
        return jbRecusar;
    }
    
    public JButton getJbPromover() {
        return jbPromover;
    }
    
    public JButton getJbRemoverAdmin() {
        return jbRemoverAdmin;
    }
    
    public JCheckBox getJcbPendentes() {
        return jcbPendentes;
    }
    
    public JCheckBox getJcbAdministradores() {
        return jcbAdministradores;
    }
    
    public void exibirMensagem(String mensagem) {
        javax.swing.JOptionPane.showMessageDialog(this, mensagem);
    }
}

