package view;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import repository.IUsuarioRepository;
import repository.INotificacaoRepository;
import com.mycompany.acessousuario.dao.UsuarioDAO;
import com.mycompany.acessousuario.dao.NotificacaoDAO;
import com.mycompany.acessousuario.model.Usuario;

/**
 *
 * @author marqu
 */
public class MainMDIView extends javax.swing.JFrame {

    /**
     * Creates new form MainMDIView
     * 
     */
    
    private static MainMDIView instance;
    
    private final IUsuarioRepository usuarioRepository;
    private final INotificacaoRepository notificacaoRepository;
    
    private MainMDIView() {
        initComponents();
        this.usuarioRepository = new UsuarioDAO();
        this.notificacaoRepository = new NotificacaoDAO();
        iniciarSistema();
    }
    
    public static MainMDIView getInstance(){
        if(instance == null){
            instance = new MainMDIView();
        }
        
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        nomeUsuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        alterarSenha = new javax.swing.JMenuItem();
        cadastrarUsuario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        enviarNotificacao = new javax.swing.JMenuItem();
        listarNotificacao = new javax.swing.JMenuItem();
        confgMenu = new javax.swing.JMenu();
        confg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeUsuario.setText("Usuario");
        desktopPane.add(nomeUsuario);
        nomeUsuario.setBounds(10, 370, 480, 16);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Usuário");

        jMenuItem2.setText("Fazer Login");
        fileMenu.add(jMenuItem2);

        alterarSenha.setMnemonic('o');
        alterarSenha.setText("Alterar Senha");
        alterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarSenhaActionPerformed(evt);
            }
        });
        fileMenu.add(alterarSenha);

        cadastrarUsuario.setMnemonic('a');
        cadastrarUsuario.setText("Cadastrar Usuário");
        cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(cadastrarUsuario);

        jMenuItem3.setText("Controle de Usuarios");
        fileMenu.add(jMenuItem3);

        jMenuItem1.setText("Deslogar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Notificações");

        enviarNotificacao.setMnemonic('t');
        enviarNotificacao.setText("Enviar ");
        enviarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarNotificacaoActionPerformed(evt);
            }
        });
        editMenu.add(enviarNotificacao);

        listarNotificacao.setMnemonic('y');
        listarNotificacao.setText("Listar");
        listarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarNotificacaoActionPerformed(evt);
            }
        });
        editMenu.add(listarNotificacao);

        menuBar.add(editMenu);

        confgMenu.setMnemonic('h');
        confgMenu.setText("Configuração");

        confg.setMnemonic('c');
        confg.setText("Confg.");
        confg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confgActionPerformed(evt);
            }
        });
        confgMenu.add(confg);

        menuBar.add(confgMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void alterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarSenhaActionPerformed
        abrirAlterarSenha();
    }//GEN-LAST:event_alterarSenhaActionPerformed
    
    private boolean focarJanelaExistente(Class<? extends javax.swing.JInternalFrame> tipoView) {
        javax.swing.JInternalFrame[] frames = desktopPane.getAllFrames();
        for (javax.swing.JInternalFrame frame : frames) {
            if (tipoView.isInstance(frame)) {
                frame.toFront();
                try {
                    frame.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                }
                return true;
            }
        }
        return false;
    }
    
    private void abrirAlterarSenha() {
        if (focarJanelaExistente(AlterarSenhaView.class)) {
            return;
        }
    }
    
    public void abrirAlterarSenhaView(Usuario usuarioAutenticado) {
        AlterarSenhaView alterarSenhaView = new AlterarSenhaView();
        new presenter.AlterarSenhaPresenter(alterarSenhaView, usuarioRepository, usuarioAutenticado);
        
        desktopPane.add(alterarSenhaView);
        alterarSenhaView.setVisible(true);
        alterarSenhaView.setLocation(100, 100);
    }

    private void cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioActionPerformed
        CadastroUsuarioView cad = new CadastroUsuarioView(usuarioRepository);
        desktopPane.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_cadastrarUsuarioActionPerformed

    private void listarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarNotificacaoActionPerformed
    }//GEN-LAST:event_listarNotificacaoActionPerformed

    private void enviarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarNotificacaoActionPerformed
    }//GEN-LAST:event_enviarNotificacaoActionPerformed

    private void confgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confgActionPerformed
        abrirConfiguracao();
    }//GEN-LAST:event_confgActionPerformed
    
    private void abrirConfiguracao() {
        if (focarJanelaExistente(ConfiguracaoView.class)) {
            return;
        }
        
        ConfiguracaoView configView = new ConfiguracaoView();
        com.mycompany.acessousuario.dao.ConfiguracaoDAO configDAO = new com.mycompany.acessousuario.dao.ConfiguracaoDAO();
        new presenter.ConfiguracaoPresenter(configView, configDAO);
        
        desktopPane.add(configView);
        configView.setVisible(true);
        configView.setLocation(100, 100);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        deslogar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void abrirLoginView() {
        if (focarJanelaExistente(LoginView.class)) {
            return;
        }
        
        LoginView login = new LoginView(this, usuarioRepository);
        desktopPane.add(login);
        login.setVisible(true);
        login.setLocation(100, 100);
    }
    
    private void deslogar() {
        javax.swing.JInternalFrame[] frames = desktopPane.getAllFrames();
        for (javax.swing.JInternalFrame frame : frames) {
            frame.dispose();
        }
        
        nomeUsuario.setText("Usuario");
        
        cadastrarUsuario.setVisible(true);
        alterarSenha.setVisible(false);
        jMenuItem3.setVisible(false);
        enviarNotificacao.setVisible(false);
        listarNotificacao.setVisible(false);
        confgMenu.setVisible(false);
        
        abrirLoginView();
        
        jMenuItem1.setVisible(false);
        jMenuItem2.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarSenha;
    private javax.swing.JMenuItem cadastrarUsuario;
    private javax.swing.JMenuItem confg;
    private javax.swing.JMenu confgMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem enviarNotificacao;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem listarNotificacao;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nomeUsuario;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }
    
    private void iniciarSistema() {
        jMenuItem1.setVisible(false);
        jMenuItem2.setVisible(true);
        jMenuItem3.setVisible(false);
        cadastrarUsuario.setVisible(true);
        alterarSenha.setVisible(false);
        enviarNotificacao.setVisible(false);
        listarNotificacao.setVisible(false);
        confgMenu.setVisible(false);
        
        LoginView login = new LoginView(this, usuarioRepository); 
        this.desktopPane.add(login);
        login.setVisible(true); 
    }
    
    public javax.swing.JMenu getFileMenu() {
        return fileMenu;
    }

    public javax.swing.JMenuItem getSaveAsMenuItem() {
        return cadastrarUsuario;
    }
    
    public void setRodapeInfo(String texto) {
        nomeUsuario.setText(texto); 
    }

    public JMenuItem getAlterarSenha() {
        return alterarSenha;
    }

    public JMenuItem getCadastrarUsuario() {
        return cadastrarUsuario;
    }

    public JMenuItem getConfg() {
        return confg;
    }

    public JMenu getConfgMenu() {
        return confgMenu;
    }

    public JMenu getEditMenu() {
        return editMenu;
    }

    public JMenuItem getEnviarNotificacao() {
        return enviarNotificacao;
    }

    public JMenuItem getExitMenuItem() {
        return exitMenuItem;
    }

    public JMenuItem getListarNotificacao() {
        return listarNotificacao;
    }
    
    public JMenuItem getDeslogarMenuItem() {
        return jMenuItem1;
    }
    
    public JMenuItem getFazerLoginMenuItem() {
        return jMenuItem2;
    }
    
    public JMenuItem getControleUsuariosMenuItem() {
        return jMenuItem3;
    }
    
}
